#!/bin/bash

#<UDF name="ssuser" Label="Sudo user username?" example="administrator" default="administrator"/>
#<UDF name="sspassword" Label="Sudo user password?" example="Execute `base64 /dev/urandom | tr -d '/+' | head -c 32` to make a password." />
#<UDF name="sspubkey" Label="SSH pubkey (installed for root and sudo user)?" example="Execute `cat ~/.ssh/id_rsa.pub` to get your key." />
#<UDF name="sshport" Label="New SSH Port (netsec)" example="Default is 22" default="22"/>

DEPLOYMENT_BASE_URL=https://raw.githubusercontent.com/fantasyui-com/linode-nodejs/master
DEPLOYMENT_BASE_DIR=/tmp

DEPLOYMENT_LIBRARY=library.sh
DEPLOYMENT_PROGRAM=program.sh

curl -o $DEPLOYMENT_BASE_DIR/$DEPLOYMENT_LIBRARY -L $DEPLOYMENT_BASE_URL/$DEPLOYMENT_LIBRARY
curl -o $DEPLOYMENT_BASE_DIR/$DEPLOYMENT_PROGRAM -L $DEPLOYMENT_BASE_URL/$DEPLOYMENT_PROGRAM

source $DEPLOYMENT_BASE_DIR/$DEPLOYMENT_LIBRARY
source $DEPLOYMENT_BASE_DIR/$DEPLOYMENT_PROGRAM
